version: 2.1
jobs:
  hello-job:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - checkout
      - run: 'echo "Hello, World!"'
workflows:
  version: 2
  my-workflow:
    jobs:
      - hello-job
